name: Rust Info
description: Rust and Bash details
runs:
  using: composite
  steps:
    - run: |
        rustup show
        cargo --version
        rustup +nightly show
        cargo +nightly --version
        cargo spellcheck --version
        bash --version
      shell: bash
