on: 
  workflow_run:
    workflows: 
      - continuous-integration
    types:
      - in_progress
      #- completed

jobs:
  comment:
    permissions: write-all

        # issues: write
        # contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: paritytech/ci-unified:bullseye-1.73.0
    timeout-minutes: 5
    # if: >
    #   github.event.workflow_run.event == 'pull_request' &&
    #   github.event.workflow_run.conclusion == 'success'
    steps:
    #   - name: Dump
    #     run: echo '${{ toJSON(github) }}'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
            #  run_id: ${{github.event.workflow_run.id }},

      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: 6738042492,
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "contract-sizes-data"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/data.zip`, Buffer.from(download.data));

      - run: unzip data.zip

      - name: Submit Comment
        env:
          GITHUB_PR_TOKEN:         ${{ secrets.github_token }}
        run: |
          #ls measurements
          cat context.out
          set -o allexport
          source context.out
          set +o allexport
          # Submit the comparison table as a comment to the PR
          echo "Submitting contract sizes diff to ${PR_COMMENTS_URL}"
          GITHUB_PR_TOKEN=${GITHUB_PR_TOKEN} scripts/contract_sizes_submit.sh ${PR_COMMENTS_URL} ${WORKFLOW_URL} <  ./contract_sizes_diff.md
              