on: 
  workflow_run:
    workflows: 
      - continuous-integration
    types:
      - completed

jobs:
  comment:
    permissions:
        issues: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v3
        with:
          name: contract-sizes_${{ github.sha }}-data
          path: measurements
      - name: Submit Comment
        env:
          GITHUB_PR_TOKEN:         ${{ secrets.github_token }}
        run: |
          cat measurements/context.out
          set -o allexport
          source measurements/context.out
          set +o allexport
          # Submit the comparison table as a comment to the PR
          echo "Submitting contract sizes diff to ${PR_COMMENTS_URL}"
          GITHUB_PR_TOKEN=${GITHUB_PR_TOKEN} ${SCRIPTS_DIR}/contract_sizes_submit.sh ${PR_COMMENTS_URL} ${WORKFLOW_URL} <  measurements/contract_sizes_diff.md
              